'use strict';var z=null,H="",I="";
(function(k){function M(b,a){null===u&&A();if(b){var c=Math.floor(1E5*Math.random()).toString();var e=R();var d=n.referrer,f=(new Date).getTime();b={p:w,s:E,v:u,e:e,g:S,c:f,n:J?"t":"f",f:K?"t":"f",l:k.location.href,r:d?d:void 0,i:c,t:b};var l="",r={};c=function(g,h){0<l.length&&(l+="\x26");var m=r[g];"undefined"===typeof m&&(m=[],r[g]=m);m.push(h);l+=g+"\x3d"+encodeURIComponent(h)};for(var p in b)if(b.hasOwnProperty(p))switch(d=b[p],typeof d){case "undefined":break;case "number":c(p,d.toString(36));
break;default:c(p,d)}"undefined"!==typeof a&&c("u",T(a));K=J=!1;L("_ss",E,1800,f,"");L("_stid",w,63072E3,f,"");c("x",U(r).toString(36));N.h(l)}else e=null;return e}function A(){V||(u=W(!1),B.pageViewId=u,O=0);M(1)}function U(b){var a=[];for(c in b)b.hasOwnProperty(c)&&a.push(c);a.sort();var c="";for(var e=0;e<a.length;++e){var d=a[e],f=b[d];c+=d;c+="\x3d";for(d=0;d<f.length;++d)c+=f[d],c+=",";c+=";"}b=unescape(encodeURIComponent(c));return X(b)}function x(){this.b=[]}function P(b,a){var c=!1,e=setTimeout(function(){c||
(c=!0,b.apply(this,arguments))},a);return function(){c||(c=!0,clearTimeout(e),b.apply(this,arguments))}}function R(){var b=O++;return u+b.toString(16)}function L(b,a,c,e,d){b=b+"\x3d"+a+"; path\x3d/; expires\x3d"+(new Date(e+1E3*c)).toUTCString()+"; max-age\x3d"+c;d&&(b+="; domain\x3d"+d);n.cookie=b}function F(b){return n.cookie.replace(new RegExp("(?:(?:^|.*;)\\s*"+b+"\\s*\\\x3d\\s*([^;]*).*$)|^.*$"),"$1")||null}function Y(b){Q.contentWindow.postMessage("22G/dzEYJ@%\x26\x3d"+b,"https://hoian.ai")}
var n=k.document,y=k.navigator,q=n.createElement("iframe");q.setAttribute("src","https://hoian.ai/s_iframe.html");q.setAttribute("id","sid_tracking");q.setAttribute("name","sname_tracking");q.setAttribute("hidden",!0);n.body.appendChild(q);var Q=n.getElementById("sid_tracking");q=function(){function b(){throw"Hoian could not initialize itself.";}var a=n.currentScript,c;if("undefined"===typeof a){a=n.getElementsByTagName("script");for(var e=new RegExp("^(:?.*/)?"+"hoian.js".replace(/[.*+?^${}()|[\]\\]/g,
"\\$\x26")+"(:?[?#].*)?$"),d=a.length-1;0<=d;--d){var f=a.item(d).src;e.test(f)&&("undefined"===typeof c?c=f:b('multiple script elements found with src\x3d"\u2026/hoian.js"'))}}else c=a.src;"undefined"===typeof c&&b('could not locate script with src\x3d".../hoian.js"');return c}();var Z=q.substr(0,1+q.lastIndexOf("/")),aa=function(){var b=[0,10,20,5,15,16,1,11,21,6,7,17,2,12,22,23,8,18,3,13,14,24,9,19,4],a=[1,32898,32906,2147516416,32907,2147483649,2147516545,32777,138,136,2147516425,2147483658,2147516555,
139,32905,32771,32770,128,32778,2147483658,2147516545,32896],c=[0,1,30,28,27,4,12,6,23,20,3,10,11,25,7,9,13,15,21,8,18,2,29,24,14];return function(e){var d,f=[];for(d=0;25>d;d+=1)f[d]=0;if(15===e.length%16)e+="\u8001";else{for(e+="\u0001";15!==e.length%16;)e+="\x00";e+="\u8000"}for(var l=0;l<e.length;l+=16){for(d=0;16>d;d+=2)f[d/2]^=e.charCodeAt(l+d)+65536*e.charCodeAt(l+d+1);for(var r=0;22>r;r+=1){var p=[];for(d=0;5>d;d+=1)p[d]=f[d]^f[d+5]^f[d+10]^f[d+15]^f[d+20];var g=[];for(d=0;5>d;d+=1){var h=
p[(d+1)%5];g[d]=p[(d+4)%5]^(h<<1|h>>>31)}p=[];for(d=0;25>d;d+=1){h=f[d]^g[d%5];var m=c[d];p[b[d]]=h<<m|h>>>32-m}for(d=0;5>d;d+=1)for(g=0;25>g;g+=5)f[g+d]=p[g+d]^~p[g+(d+1)%5]&p[g+(d+2)%5];f[0]^=a[r]}}e=[];for(d=0;8>d;++d)l=f[d],e.push(l&255,l>>>8,l>>>16,l>>>24);return e}}(),X=function(){function b(a,c){var e=c&65535;return((c-e)*a|0)+(e*a|0)|0}return function(a,c){var e=a.length;c="undefined"!==typeof c?c:0;for(var d=e&-4,f,l=0;l<d;l+=4)f=a.charCodeAt(l)&255|(a.charCodeAt(l+1)&255)<<8|(a.charCodeAt(l+
2)&255)<<16|(a.charCodeAt(l+3)&255)<<24,f=b(f,3432918353),f=(f&131071)<<15|f>>>17,f=b(f,461845907),c^=f,c=(c&524287)<<13|c>>>19,c=5*c+3864292196|0;f=0;switch(e%4){case 3:f=(a.charCodeAt(d+2)&255)<<16;case 2:f|=(a.charCodeAt(d+1)&255)<<8;case 1:f|=a.charCodeAt(d)&255,f=b(f,3432918353),f=b((f&131071)<<15|f>>>17,461845907),c^=f}a=c^e;a=b(a^a>>>16,2246822507);a=b(a^a>>>13,3266489909);return a^a>>>16}}(),W=function(){function b(){if("ActiveXObject"in k){var g="activex:";for(var h=0,m=r.length;h<m;++h){var t=
r[h];try{var v=new ActiveXObject(t);g+="1";"getVersions"in v?g+="("+v.getVersions()+")":"getVariable"in v&&(g+="("+v.getVariable("$version")+")")}catch(G){g+="0"}}}else g="";return g}function a(){var g=y.mimeTypes;if(g){var h="plugins:";for(var m=0,t=l.length;m<t;++m)h+=l[m]in g?"1":"0"}else h="";return h}var c=Math,e=k.crypto||k.msCrypto,d="undefined"!==typeof e&&"undefined"!==typeof e.getRandomValues,f=d?function(g){g=new Uint8Array(g);e.getRandomValues(g);return g}:function(g){for(var h=Array(g),
m=0;m<g;++m)h[m]=c.floor(256*c.random());return h},l="application/pdf video/quicktime video/x-msvideo audio/x-pn-realaudio-plugin audio/mpeg3 application/googletalk application/x-mplayer2 application/x-director application/x-shockwave-flash application/x-java-vm application/x-googlegears application/x-silverlight".split(" "),r=["ShockwaveFlash.ShockwaveFlash.1","AcroPDF.PDF","AgControl.AgControl","QuickTime.QuickTime"],p=(new Date).getTime();return function(g){var h=(new Date).getTime().toString(36);
for(var m=k.location.href||"",t=f(32),v="",G=0;G<t.length;++G)v+=String.fromCharCode(t[G]);h=[h,m,v];d||h.push.apply(h,[y.userAgent||"",y.platform||"",y.language||"",y.systemLanguage||"",y.userLanguage||"",a(),b()]);h=aa(h.join(""));m="";t=0;for(v=h.length;t<v;++t)m+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxzy0123456789~_".charAt(h[t]&63);d||(m+="!");h=m;return"0:"+(g?p.toString(36)+":"+h:h)}}(),w,E,u=function(b){var a=b.indexOf("#");b=-1!==a?b.substring(a+1):null;if(null!==b&&-1!==b.indexOf("/"))throw"DVT not initialized correctly; page view ID may not contain a slash ('/').";
return b}(q),J,K,S=F("_ga"),V=!!u;(function(){I=F("_stid");H=F("_ss");null!=z&&""!==z?w=z:((J=!I)?w=(new Date).getTime().toString()+Math.floor(100*Math.random()).toString():w=I,Q.onload=function(){k.addEventListener("message",Y(w),!1)});(K=!H)||!n.referrer?E=Math.floor(1E6*Math.random()).toString()+"."+Math.round((new Date).getTime()/1E3):E=H})();var O=0;x.prototype.h=function(b){var a=this.b;a.push(b);1===a.length&&this.j()};x.prototype.j=function(){var b=this.b[0];switch(typeof b){case "string":this.m(b);
break;case "function":this.o(b);break;default:this.a()}};x.prototype.m=function(b){var a=this,c=new Image(1,1),e=P(function(){a.a()},2E3);c.onload=e;c.onerror=e;c.src=Z+"hoian-event?"+b};x.prototype.o=function(b){b();this.a()};x.prototype.a=function(){var b=this.b;b.shift();0<b.length&&this.j()};var N=new x,T=function(){function b(){this.a="";this.h=null}b.prototype.G=function(){this.b("(")};b.prototype.C=function(){this.h=null;this.b(")")};b.prototype.F=function(){this.b("a")};b.prototype.B=function(){this.b(".")};
b.prototype.D=function(a){this.h=a};b.prototype.b=function(a,c){this.a+=a;null!==this.h&&(this.a+=b.a(this.h),this.a+="!",this.h=null);c&&(this.a+=c)};b.a=function(){var a=/[~!]/g;return function(c){return c.replace(a,"~$\x26")}}();b.prototype.A=function(a){this.b("s",b.a(a)+"!")};b.prototype.u=function(a){if(isFinite(a)){var c=a===Math.floor(a)?a.toString(36):null,e=a.toExponential();a=String(a);null!==c&&c.length<=e.length&&c.length<=a.length?this.b("d",c+"!"):this.b("j",(e.length<a.length?e:a)+
"!")}else this.encode(null,!1)};b.prototype.m=function(a){this.b(a?"t":"f")};b.prototype.I=function(){this.b("n")};b.prototype.j=function(a){this.F();for(var c=0;c<a.length;++c)this.encode(a[c],!0);this.B()};b.prototype.o=function(){function a(c,e){for(e=e.toString();e.length<c;)e="0"+e;return e}return function(c){c=isFinite(c.valueOf())?c.getUTCFullYear()+"-"+a(2,c.getUTCMonth()+1)+"-"+a(2,c.getUTCDate())+"T"+a(2,c.getUTCHours())+":"+a(2,c.getUTCMinutes())+":"+a(2,c.getUTCSeconds())+"."+a(3,c.getUTCMilliseconds())+
"Z":null;this.encode(c,!1)}}();b.prototype.H=function(a){this.G();for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&(this.D(c),this.encode(a[c],!1));this.C()};b.prototype.w=function(a,c){if(null===a)this.I();else if("function"===typeof a.toJSON)this.encode(a.toJSON(),c);else switch(Object.prototype.toString.call(a)){case "[object Array]":this.j(a);break;case "[object Date]":this.o(a);break;default:this.H(a)}};b.prototype.encode=function(a,c){switch(typeof a){case "string":this.A(a);break;
case "number":this.u(a);break;case "boolean":this.m(a);break;case "object":this.w(a,c);break;case "undefined":c&&this.encode(null,!1);break;default:throw"Cannot encode of type: "+typeof a;}};b.b=function(a){var c=new b;c.encode(a,!1);a=c.a;return""!==a?a:void 0};return b.b}();(function(b,a,c){b.addEventListener?b.addEventListener(a,c,!1):b.attachEvent&&b.attachEvent("on"+a,c)})(k,"message",function(b){"https://hoian.ai"===b.origin&&b.data&&"-"!==b.data&&(b=b.data.split("\x3d"),"22G/dzEYJ@%\x26"===
b[0]&&(z=b[1],L("_stid",z,63072E3,(new Date).getTime(),"")))});var B={event_click:2,event_rating:5,event_user_info:7,event_add_to_cart:3,event_remove_from_cart:4,event_checkout:6,event_view:8,social_other:1,social_google:2,social_zalo:3,social_twitter:4,social_facebook:5,pageViewId:u,signal:M,whenCommitted:function(b,a){"undefined"!==typeof a&&(b=P(b,a));N.h(b)},getTrackingId:function(){return F("_stid")},getUserId:function(){return null}};if("object"!==typeof k.hoian){"function"===typeof k.define&&
k.define.amd?k.define(function(){return B}):"undefined"!==typeof k.module&&k.module.exports?k.module.exports=B:k.hoian=B;if("undefined"!==typeof n.hidden){var C="hidden";var D="visibilitychange"}else"undefined"!==typeof n.mozHidden?(C="mozHidden",D="mozvisibilitychange"):"undefined"!==typeof n.msHidden?(C="msHidden",D="msvisibilitychange"):"undefined"!==typeof n.webkitHidden&&(C="webkitHidden",D="webkitvisibilitychange");n[C]?n.addEventListener&&n.removeEventListener?n.addEventListener(D,function a(){null===
u&&!1===n[C]&&A();null!==u&&n.removeEventListener(D,a)}):A():A();"onpageshow"in k&&"onpagehide"in k&&k.addEventListener&&k.removeEventListener?k.addEventListener("pagehide",function c(){k.removeEventListener("pagehide",c);k.addEventListener("pageshow",function(){A()})}):(q=k.history)&&typeof("undefined"!==q.navigationMode)&&(q.navigationMode="compatible")}return B})("undefined"!==typeof window?window:this);